### ISSUE TITLE
Add code formatting validation both local and via CI hook 

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#29]
#### Description
An automatic tool to ensure source code follows the same format

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add necessary configuration to run formatting in source code
- [ ] Add instructions to format source code locally
- [ ] Conform source code to new standard
- [ ] Add CI Hook to ensure new standard

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).
