### ISSUE TITLE
Add Deoxygen to build documentation

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#3]
#### Description
Integrate existing CMake configuration to Deoxygen in order to build documentation

#### Files
* CMakeLists.txt

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add Deoxygen/CMake configuration to build documentation 
- [ ] Do changes if necessary to build existing documentation for seq_list
- [ ] Describe as clearly as possible the steps to build the documentation in the README.

**Comment by Sabihashaik** [comment]
Hi @Benardi ! I'd like to attempt this! 😄

**Comment by Sabihashaik** [comment]
I'm still working on this, will try to send across a PR by today for the same 😃

**Comment by Benardi** [comment]
No problem, thanks for the help.
