### ISSUE TITLE
Add algorithms of sorting in linear time

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#31]
#### Description
Add radix, counting and bucket sort 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add the implementations for radix, counting and bucket sort 
- [ ] Add unit tests for each of the algorithms
- [ ] Add documentation for each of the algorithms
