### ISSUE TITLE
Make register's key and satellite data of generic type 

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#32]
#### Description
Allow any type for register's key and satellite data as long as routine for key comparison  is provided

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Update Register header with key and satellite data of generic type 
- [ ] Conform data structures implementation to new Register format
- [ ] Conform unit tests to new Register format
