### ISSUE TITLE
Add Shortest Path Algorithms

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#37]
#### Description
Add the following Shortest Path Algorithms:

* Dijkstra's algorithm
* Bellman–Ford algorithm
* Floyd–Warshall algorithm

#### Tasks
- [ ] Add the necessary representations of a graph (struct or array)
- [ ] Add implementation, tests and documentation for Dijkstra's algorithm
- [ ] Add implementation, tests and documentation for Bellman–Ford algorithm
- [ ] Add implementation, tests and documentation for Floyd–Warshall algorithm
