### ISSUE TITLE
Add Register struct to Heap module

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#38]
#### Description
Edit Heap module to replace int data type for Register struct.
Conform dependent modules : `max_pq` and `sort`

#### Files
* heap:
  + `src/heap.c`
  + `src/include/heap.h`
  + `tests/test_heap.c`
* max_pq:
  + `src/max_pq.c`
  + `src/include/max_pq.h`
  + `tests/test_max_pq.c`
* sort:
  + `src/sort.c`
  + `src/include/sort.h`
  + `tests/test_sort.c`

#### Tasks
- [ ] Update heap, max_pq and sort module source code
- [ ] Update heap, max_pq and sort module header
- [ ] Update heap, max_pq and sort module's test suite
