### ISSUE TITLE
Add algorithms for search in a graph

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#42]
#### Description
Add the following algorithms for search in a graph:

* BFS
* DFS

#### Tasks
- [ ] Add the necessary representations of a graph (struct or array)
- [ ] Add implementation, tests and documentation for BFS
- [ ] Add implementation, tests and documentation for DFS
