### ISSUE TITLE
Allow tests by build mode. Make CI debug mode

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#43]
#### Description
Allow tests according to build mode.
 + Skip tests altogether on Release and MinSizeRel mode
 + Make valgrind checks only on Debug Mode
  + Set CI to debug mode

#### Tasks
- [ ] Condition tests build according to build mode
- [ ] Edit CI configuration to create a build in debug mode
- [ ] Update source /tests in case an error is found
