### ISSUE TITLE
Add resizable array

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#46]
#### Description
Add module with the implementation of a resizable array, an "ArrayList"

#### Tasks
- [ ] Add implementation for module "ArrayList".
- [ ] Add unit tests for module "ArrayList".
- [ ] Add documentation for module "ArrayList".
