### ISSUE TITLE
Remove void pointer from Register's key

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#48]
#### Description
It has become increasingly counter-productive to employ a void pointer to store a primitive type (e.g., an integer or float). We should devise a new and more convenient strategy to store a primitive type in our Register.

#### Files

- `src/include/register.h`

#### Tasks

- [ ] Update Register struct
- [ ] Update source code and tests of modules that use the Register struct
- [ ] Update documentation of modules that use the Register struct
