### ISSUE TITLE
Add "String Builder"

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#54]
#### Description
Add a module to provide string/array of characters related utilities such as append, delete, and insert at. 

#### Tasks

- [ ] Add a representation for the StringBuilder
- [ ] Add implementation for StringBuilder's functionalities
- [ ] Add documentation for StringBuilder's functionalities
- [ ] Add tests for StringBuilder's functionalities
