### ISSUE TITLE
Integrate Deoxygen/Cmake documentation to Sphinx using Breathe  

### ISSUE THREAD

**Issue by Benardi** [Benardi/sibylline#6]
#### Description
Replace existing `Doxygen + CMake` documentation for a documentation using `Sphinx + Breathe + Doxygen + CMake`

#### Files
* `CMakeLists.txt` - Cmake root configuration
* `docs/Doxyfile` -Deoxygen configuration file

#### Tasks
- [ ] Add Sphinx / Breathe
- [ ] Integrate Sphinx + Breathe + Doxygen + CMake
- [ ] Make adjustments to generate docs for existing module

OBS: For the Sphinx docs there's no need to add the README as the docs' primary page,
